

<header>
<link href="./css/zeidon_allrelative.css" rel="stylesheet" type="text/css">
   <div class="layoutgrid">
      <div id="logo" class="layoutunit one-quarter align-left">
         <img src="./images/logo.png" alt="logo" max-height="125px" max-width="125px">
         <!-- Before Logo-->
      </div>
      <div class="layoutunit half align-middle">
      	<h1>Zeidon Base</h1>
      </div>
   </div>
</header>
